<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-GAD15EJN" name="shoppingCart.TestAddCart" tests="16" failures="2" timestamp="6 Dec 2019 07:19:21 GMT" time="314.609" errors="0">
  <testcase name="test_03_AddCartDifferentProperty" time="20.519" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_10_addGoodsNumFail02" time="13.599" classname="shoppingCart.TestAddCart">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at shoppingCart.TestAddCart.test_10_addGoodsNumFail02(TestAddCart.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_10_addGoodsNumFail02 -->
  <testcase name="test_03_AddCartDifferentProperty" time="20.471" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_05_addGoodsNuByButton3" time="26.970" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.494" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.498" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_12_addGoodsNumFail03" time="11.346" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_Open2" time="17.297" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_Open1" time="20.811" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_06_addGoodsNuByButton2" time="27.025" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_04_addGoodsNuByButton1" time="10.812" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.443" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_08_addGoodsNumFail01" time="6.691" classname="shoppingCart.TestAddCart">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at shoppingCart.TestAddCart.test_08_addGoodsNumFail01(TestAddCart.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_08_addGoodsNumFail01 -->
  <testcase name="testLogin" time="36.548" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.658" classname="shoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.427" classname="shoppingCart.TestAddCart"/>
</testsuite> <!-- shoppingCart.TestAddCart -->
